# Service definition for Vault cluster with a minimum of 3 nodes.
# Nodes will use Triton CNS for the service (passed in via the CONSUL
# env var) to find each other and bootstrap the cluster.
vault:
    image: autopilotpattern/vault:latest
    labels:
      - triton.cns.services=vault
    restart: always
    mem_limit: 128m
    dns_search:
      - svc.${TRITON_ACCOUNT}.${TRITON_DC}.cns.joyent.com
    env_file:
      - _env
    command: >
      /usr/local/bin/containerpilot
      /bin/consul agent -server
        -bootstrap-expect 3
        -config-dir=/etc/consul
        -ui-dir /ui


# Although we're using Consul as the backing store for Vault, we don't
# want to use that same store for general service discovery. So we'll
# start a single-node Consul cluster to demonstrate registering Vault
# with service discovery. In production we'll want to use an HA cluster.
consul:
    image: consul:v0.7.0
    restart: always
    mem_limit: 128m
    expose:
      - 53
      - 8300
      - 8301
      - 8302
      - 8400
      - 8500
    ports:
      - 8500
    dns:
       - 127.0.0.1
    labels:
        - triton.cns.services=consul
    command: agent -server -client=0.0.0.0 -bootstrap -ui
