version: '2'

# Service definition for Vault cluster with a minimum of 3 nodes.
# For local development we use Compose v2 so that we have an automatically
# created user-defined network and internal DNS for the name "vault".
# Nodes will use Docker DNS for the service (passed in via the env vars)
# to find each other and bootstrap the cluster.
services:
  vault:
    build: .
    restart: always
    mem_limit: 128m
    ports:
        - 8500
    dns:
       - 127.0.0.1
    environment:
      - VAULT=vault
    command: >
      /usr/local/bin/containerpilot
      /bin/consul agent -server
        -bootstrap-expect 3
        -config-dir=/etc/consul
        -ui-dir /ui
