version: '2'

# Service definition for Vault cluster with a minimum of 3 nodes.
# For local development we use Compose v2 so that we have an automatically
# created user-defined network and internal DNS for the name "vault".
# Nodes will use Docker DNS for the service (passed in via the env vars)
# to find each other and bootstrap the cluster.
services:
  vault:
    build: .
    restart: always
    mem_limit: 128m
    ports:
        - 8500
    dns:
       - 127.0.0.1
    environment:
      - CONSUL=consul
      - VAULT=vault
    command: >
      /usr/local/bin/containerpilot
      /bin/consul agent -server
        -bootstrap-expect 3
        -config-dir=/etc/consul
        -ui-dir /ui

  # Although we're using Consul as the backing store for Vault, we don't
  # want to use that same store for general service discovery. So we'll
  # start a single-node Consul cluster to demonstrate registering Vault
  # with service discovery. In production we'll want to use an HA cluster.
  consul:
      image: consul:v0.7.0
      restart: always
      mem_limit: 128m
      expose:
        - 53
        - 8300
        - 8301
        - 8302
        - 8400
        - 8500
      ports:
        - 8500
      dns:
         - 127.0.0.1
      labels:
          - triton.cns.services=consul
      command: agent -server -client=0.0.0.0 -bootstrap -ui
